/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientUploadRouteImport } from './routes/patient.upload'
import { Route as PatientRecordsRouteImport } from './routes/patient.records'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientRecordsIdRouteImport } from './routes/patient.records.$id'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientUploadRoute = PatientUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRecordsRoute = PatientRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRecordsIdRoute = PatientRecordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientRecordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/records': typeof PatientRecordsRouteWithChildren
  '/patient/upload': typeof PatientUploadRoute
  '/patient/records/$id': typeof PatientRecordsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/records': typeof PatientRecordsRouteWithChildren
  '/patient/upload': typeof PatientUploadRoute
  '/patient/records/$id': typeof PatientRecordsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/records': typeof PatientRecordsRouteWithChildren
  '/patient/upload': typeof PatientUploadRoute
  '/patient/records/$id': typeof PatientRecordsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/patient'
    | '/patient/dashboard'
    | '/patient/records'
    | '/patient/upload'
    | '/patient/records/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/patient'
    | '/patient/dashboard'
    | '/patient/records'
    | '/patient/upload'
    | '/patient/records/$id'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/patient'
    | '/patient/dashboard'
    | '/patient/records'
    | '/patient/upload'
    | '/patient/records/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/upload': {
      id: '/patient/upload'
      path: '/upload'
      fullPath: '/patient/upload'
      preLoaderRoute: typeof PatientUploadRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/records': {
      id: '/patient/records'
      path: '/records'
      fullPath: '/patient/records'
      preLoaderRoute: typeof PatientRecordsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/records/$id': {
      id: '/patient/records/$id'
      path: '/$id'
      fullPath: '/patient/records/$id'
      preLoaderRoute: typeof PatientRecordsIdRouteImport
      parentRoute: typeof PatientRecordsRoute
    }
  }
}

interface PatientRecordsRouteChildren {
  PatientRecordsIdRoute: typeof PatientRecordsIdRoute
}

const PatientRecordsRouteChildren: PatientRecordsRouteChildren = {
  PatientRecordsIdRoute: PatientRecordsIdRoute,
}

const PatientRecordsRouteWithChildren = PatientRecordsRoute._addFileChildren(
  PatientRecordsRouteChildren,
)

interface PatientRouteChildren {
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientRecordsRoute: typeof PatientRecordsRouteWithChildren
  PatientUploadRoute: typeof PatientUploadRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientDashboardRoute: PatientDashboardRoute,
  PatientRecordsRoute: PatientRecordsRouteWithChildren,
  PatientUploadRoute: PatientUploadRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
